name: Web-Cloud-PC-New

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Preparing Desktop Environment
        run: |
          # استفاده از یک ایمیج معتبر و تست شده
          # این ایمیج یوزرنیم و پسورد نمی‌خواهد و مستقیم روی پورت 80 باز می‌شود
          docker run -d -p 6080:80 --name desktop dorowu/ubuntu-desktop-lxde-vnc
          
      - name: Setting Up Tunnel (Ngrok)
        run: |
          # نصب Ngrok
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install ngrok
          
          # توکن شما
          ngrok authtoken cr_3DUVyCYuAWpjaqEkrgUO0t8RO2A
          
          echo "در حال ایجاد لینک جدید..."
          ngrok http 6080
