name: Web-Cloud-PC-Cloudflare

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Preparing Desktop Environment
        run: |
          # اجرای دسکتاپ
          docker run -d -p 6080:80 --name desktop dorowu/ubuntu-desktop-lxde-vnc
          
      - name: Setting Up Cloudflare Tunnel
        run: |
          # نصب ابزار کلودفلر (بدون نیاز به اکانت و توکن)
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb
          
          echo "در حال ایجاد لینک مستقیم... لطفا صبر کنید"
          # ایجاد لینک عمومی
          cloudflared tunnel --url http://localhost:6080
